"""add_tenant_calendar_configs

Revision ID: 2d7b5251fa89
Revises: 4b209c6a085d
Create Date: 2026-03-01 21:15:49.887028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d7b5251fa89'
down_revision: Union[str, Sequence[str], None] = '4b209c6a085d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_calendar_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('google_credentials_json', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('business_hours_start', sa.Time(), nullable=False),
    sa.Column('business_hours_end', sa.Time(), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_between_slots', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_calendar_configs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_calendar_configs')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_calendar_configs_tenant_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_calendar_configs')
    # ### end Alembic commands ###
