"""add_bookings_and_calendar_config

Revision ID: 4b209c6a085d
Revises: cee53bcf77f3
Create Date: 2026-03-01 21:10:13.717634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b209c6a085d'
down_revision: Union[str, Sequence[str], None] = 'cee53bcf77f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_name', sa.String(length=200), nullable=False))
    op.add_column('bookings', sa.Column('provider_name', sa.String(length=200), nullable=True))
    op.add_column('bookings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bookings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bookings', sa.Column('patient_name', sa.String(length=200), nullable=True))
    op.add_column('bookings', sa.Column('patient_rut', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_reason', sa.String(length=500), nullable=True))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    booking_status = postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus')
    booking_status.create(op.get_bind())
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='bookingstatusenum'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'),
               postgresql_using="UPPER(status::text)::bookingstatus",
               nullable=False)
    op.alter_column('bookings', 'google_event_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_bookings_contact_id'), table_name='bookings')
    op.create_index('ix_bookings_tenant_start', 'bookings', ['tenant_id', 'start_time'], unique=False)
    op.create_index('ix_bookings_tenant_status', 'bookings', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('fk_bookings_conversation_id_conversations'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_contact_id_contacts'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_tenant_id_tenants'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_tenant_id_tenants'), 'bookings', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_contact_id_contacts'), 'bookings', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_conversation_id_conversations'), 'bookings', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('bookings', 'datetime')
    op.drop_column('bookings', 'service')
    op.drop_column('bookings', 'duration_min')
    op.drop_column('bookings', 'reminder_sent')
    op.drop_column('bookings', 'professional')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('professional', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('reminder_sent', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('duration_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('service', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_bookings_conversation_id_conversations'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_contact_id_contacts'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_tenant_id_tenants'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_tenant_id_tenants'), 'bookings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_bookings_contact_id_contacts'), 'bookings', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_bookings_conversation_id_conversations'), 'bookings', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_bookings_tenant_status', table_name='bookings')
    op.drop_index('ix_bookings_tenant_start', table_name='bookings')
    op.create_index(op.f('ix_bookings_contact_id'), 'bookings', ['contact_id'], unique=False)
    op.alter_column('bookings', 'google_event_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'),
               type_=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='bookingstatusenum'),
               postgresql_using="LOWER(status::text)::bookingstatusenum",
               nullable=True)
    op.execute("DROP TYPE bookingstatus")
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'cancelled_reason')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'google_calendar_id')
    op.drop_column('bookings', 'patient_rut')
    op.drop_column('bookings', 'patient_name')
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    op.drop_column('bookings', 'provider_name')
    op.drop_column('bookings', 'service_name')
    # ### end Alembic commands ###
