"""update_knowledgecategoryenum

Revision ID: 6ed7d3301b8a
Revises: e18d8ef95eeb
Create Date: 2026-02-28 08:03:53.620133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed7d3301b8a'
down_revision: Union[str, Sequence[str], None] = 'e18d8ef95eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE knowledgecategoryenum ADD VALUE IF NOT EXISTS 'service';")
        op.execute("ALTER TYPE knowledgecategoryenum ADD VALUE IF NOT EXISTS 'policy';")
        op.execute("ALTER TYPE knowledgecategoryenum ADD VALUE IF NOT EXISTS 'promo';")
    
    # Update existing data from old spanish values to new english values
    op.execute("UPDATE knowledge_base SET category = 'service' WHERE category::text = 'servicios';")
    op.execute("UPDATE knowledge_base SET category = 'policy' WHERE category::text = 'politicas';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
