"""add_bookings_and_calendar_config

Revision ID: 9e19845a3042
Revises: 2d7b5251fa89
Create Date: 2026-03-18 19:36:37.268957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e19845a3042'
down_revision: Union[str, Sequence[str], None] = '2d7b5251fa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
